chore: optimize benchmark flow

diff --git a/.github/workflows/benchmark-prs.yml b/.github/workflows/benchmark-prs.yml
--- a/.github/workflows/benchmark-prs.yml
+++ b/.github/workflows/benchmark-prs.yml
@@ -61,142 +61,36 @@ jobs:
         shell: bash
         run: echo "The SAFE_PEERS variable has been set to $SAFE_PEERS"
 
-      ########################
-      ### Benchmark        ###
-      ########################
-      - name: Bench `safe`
-        shell: bash
-        # Criterion outputs the actual bench results to stderr "2>&1 tee output.txt" takes stderr,
-        # passes to tee which displays it in the terminal and writes to output.txt
-        run: |
-          cargo criterion --features=local-discovery --message-format=json 2>&1 | tee -a output.txt
-          cat output.txt | rg benchmark-complete | jq -s 'map({
-          name: (.id | split("/"))[-1],
-          unit: "MiB/s",
-          value: ((if .throughput[0].unit == "KiB/s" then (.throughput[0].per_iteration / (1024*1024*1024)) else (.throughput[0].per_iteration / (1024*1024)) end) / (.mean.estimate / 1e9))
-          })' > files-benchmark.json
-      - name: Store benchmark result
-        uses: benchmark-action/github-action-benchmark@v1
-        with:
-          # What benchmark tool the output.txt came from
-          tool: 'customBiggerIsBetter'
-          output-file-path: files-benchmark.json
-          # Where the previous data file is stored
-          external-data-json-path: ./cache/benchmark-data.json
-          # Workflow will fail when an alert happens
-          fail-on-alert: true
-          # GitHub API token to make a commit comment
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          # Enable alert commit comment
-          comment-on-alert: true
-          # 200% regression will result in alert
-          alert-threshold: '200%'
-          # Enable Job Summary for PRs
-          summary-always: true
+      #########################
+      ### Upload large file ###
+      #########################
 
-      # The generated large single file (around 450MB) may vary little bit along the releases
-      - name: Zip release folder 
+      - name: Fund cli wallet
         shell: bash
-        run: tar -czvf release_zip.tar.gz ./target/release
-
-      - name: Check release folder size
-        shell: bash
-        run: |
-          file_size=$(stat -c "%s" release_zip.tar.gz)
-          file_size_mb=$(bc <<< "scale=2; $file_size / (1024 * 1024)")
-          echo "file size: $file_size"
-          echo "file size mb: $file_size_mb"
-
-      - name: Start a client instance to compare memory usage
-        shell: bash
-        run: cargo run --bin safe --release -- --log-output-dest=data-dir files upload the-test-data.zip
+        run: target/release/safe --log-output-dest=data-dir wallet get-faucet 127.0.0.1:8000
         env:
           SN_LOG: "all"
 
-      #########################
-      ### Stop Network      ###
-      #########################
-      
-      - name: Stop the local network
-        if: always()
-        uses: maidsafe/sn-local-testnet-action@main
-        with:
-          action: stop
-          log_file_prefix: safe_test_logs_benchmark
-          platform: ubuntu-latest
-
-      - name: Upload Faucet folder
-        uses: actions/upload-artifact@main
-        with:
-          name: faucet_folder
-          path: /home/runner/.local/share/safe/test_faucet
-        continue-on-error: true
-        if: always()
-
-      #########################
-      ### Mem Analysis      ###
-      #########################
-
-      # The large file uploaded will increase node's peak mem usage a lot
-      - name: Check node memory usage
+      - name: Start a client instance to compare memory usage
         shell: bash
-        run: |
-          node_peak_mem_limit_mb="100" # mb
-          peak_mem_usage=$(
-            rg '"memory_used_mb":[^,]*' $NODE_DATA_PATH/*/logs/* -o --no-line-number --no-filename | 
-            awk -F':' '/"memory_used_mb":/{print $2}' | 
-            sort -n | 
-            tail -n 1
-          )
-         
-          echo "Memory usage: $peak_mem_usage MB"
-          if (( $(echo "$peak_mem_usage > $node_peak_mem_limit_mb" | bc -l) )); then
-            echo "Node memory usage exceeded threshold: $peak_mem_usage MB"
-            exit 1
-          fi
-          # Write the node memory usage to a file
-          echo '[
-              {
-                  "name": "node-memory-usage-through-safe-benchmark",
-                  "value": '$peak_mem_usage',
-                  "unit": "MB"
-              }
-          ]' > node_memory_usage.json
+        run: target/release/safe --log-output-dest=data-dir files upload the-test-data.zip
+        env:
+          SN_LOG: "all"
 
-      - name: check node_memory_usage.json
-        shell: bash
-        run: cat node_memory_usage.json
-
-      - name: Alert for node memory usage
-        uses: benchmark-action/github-action-benchmark@v1
-        with:
-          tool: 'customSmallerIsBetter'
-          output-file-path: node_memory_usage.json
-          # Where the previous data file is stored
-          external-data-json-path: ./cache/node-mem-usage.json
-          # Workflow will fail when an alert happens
-          fail-on-alert: true
-          # GitHub API token to make a commit comment
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          # Enable alert commit comment
-          comment-on-alert: true
-          # Comment on the PR
-          comment-always: true
-          # 200% regression will result in alert
-          alert-threshold: '200%'
-          # Enable Job Summary for PRs
-          summary-always: true
+      ###########################
+      ### Client Mem Analysis ###
+      ###########################
 
       - name: Check client memory usage
         shell: bash
         run: |
           client_peak_mem_limit_mb="2000" # mb
           client_avg_mem_limit_mb="700" # mb
-          
+
           peak_mem_usage=$(
-            rg '"memory_used_mb":[^,]*' $CLIENT_DATA_PATH/logs/safenode.* -o --no-line-number --no-filename | 
-            awk -F':' '/"memory_used_mb":/{print $2}' | 
-            sort -n | 
+            rg '"memory_used_mb":[^,]*' $CLIENT_DATA_PATH/logs/safenode.* -o --no-line-number --no-filename |
+            awk -F':' '/"memory_used_mb":/{print $2}' |
+            sort -n |
             tail -n 1
           )
           echo "Peak memory usage: $peak_mem_usage MB"
@@ -206,7 +100,7 @@ jobs:
           fi
 
           total_mem=$(
-            rg '"memory_used_mb":[^,]*' $CLIENT_DATA_PATH/logs/safenode.* -o --no-line-number --no-filename | 
+            rg '"memory_used_mb":[^,]*' $CLIENT_DATA_PATH/logs/safenode.* -o --no-line-number --no-filename |
             awk -F':' '/"memory_used_mb":/ {sum += $2} END {printf "%.0f\n", sum}'
           )
           num_of_times=$(
@@ -255,6 +149,113 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           # Enable alert commit comment
           comment-on-alert: true
+          # 200% regression will result in alert
+          alert-threshold: '200%'
+          # Enable Job Summary for PRs
+          summary-always: true
+
+      ########################
+      ### Benchmark        ###
+      ########################
+      - name: Bench `safe`
+        shell: bash
+        # Criterion outputs the actual bench results to stderr "2>&1 tee output.txt" takes stderr,
+        # passes to tee which displays it in the terminal and writes to output.txt
+        run: |
+          cargo criterion --features=local-discovery --message-format=json 2>&1 | tee -a output.txt
+          cat output.txt | rg benchmark-complete | jq -s 'map({
+          name: (.id | split("/"))[-1],
+          unit: "MiB/s",
+          value: ((if .throughput[0].unit == "KiB/s" then (.throughput[0].per_iteration / (1024*1024*1024)) else (.throughput[0].per_iteration / (1024*1024)) end) / (.mean.estimate / 1e9))
+          })' > files-benchmark.json
+      - name: Store benchmark result
+        uses: benchmark-action/github-action-benchmark@v1
+        with:
+          # What benchmark tool the output.txt came from
+          tool: 'customBiggerIsBetter'
+          output-file-path: files-benchmark.json
+          # Where the previous data file is stored
+          external-data-json-path: ./cache/benchmark-data.json
+          # Workflow will fail when an alert happens
+          fail-on-alert: true
+          # GitHub API token to make a commit comment
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          # Enable alert commit comment
+          comment-on-alert: true
+          # 200% regression will result in alert
+          alert-threshold: '200%'
+          # Enable Job Summary for PRs
+          summary-always: true
+
+      #########################
+      ### Stop Network      ###
+      #########################
+      
+      - name: Stop the local network
+        if: always()
+        uses: maidsafe/sn-local-testnet-action@main
+        with:
+          action: stop
+          log_file_prefix: safe_test_logs_benchmark
+          platform: ubuntu-latest
+
+      - name: Upload Faucet folder
+        uses: actions/upload-artifact@main
+        with:
+          name: faucet_folder
+          path: /home/runner/.local/share/safe/test_faucet
+        continue-on-error: true
+        if: always()
+
+      #########################
+      ### Node Mem Analysis ###
+      #########################
+
+      # The large file uploaded will increase node's peak mem usage a lot
+      - name: Check node memory usage
+        shell: bash
+        run: |
+          node_peak_mem_limit_mb="100" # mb
+          peak_mem_usage=$(
+            rg '"memory_used_mb":[^,]*' $NODE_DATA_PATH/*/logs/* -o --no-line-number --no-filename | 
+            awk -F':' '/"memory_used_mb":/{print $2}' | 
+            sort -n | 
+            tail -n 1
+          )
+         
+          echo "Memory usage: $peak_mem_usage MB"
+          if (( $(echo "$peak_mem_usage > $node_peak_mem_limit_mb" | bc -l) )); then
+            echo "Node memory usage exceeded threshold: $peak_mem_usage MB"
+            exit 1
+          fi
+          # Write the node memory usage to a file
+          echo '[
+              {
+                  "name": "node-memory-usage-through-safe-benchmark",
+                  "value": '$peak_mem_usage',
+                  "unit": "MB"
+              }
+          ]' > node_memory_usage.json
+
+      - name: check node_memory_usage.json
+        shell: bash
+        run: cat node_memory_usage.json
+
+      - name: Alert for node memory usage
+        uses: benchmark-action/github-action-benchmark@v1
+        with:
+          tool: 'customSmallerIsBetter'
+          output-file-path: node_memory_usage.json
+          # Where the previous data file is stored
+          external-data-json-path: ./cache/node-mem-usage.json
+          # Workflow will fail when an alert happens
+          fail-on-alert: true
+          # GitHub API token to make a commit comment
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          # Enable alert commit comment
+          comment-on-alert: true
+          # Comment on the PR
+          comment-always: true
           # 200% regression will result in alert
           alert-threshold: '200%'
           # Enable Job Summary for PRs
