ci: assert faucet funded before upload

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -1136,6 +1136,8 @@ jobs:
   #   if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
   #   name: Replication bench with heavy upload
   #   runs-on: ubuntu-latest
+  #   env:
+  #     CLIENT_DATA_PATH: /home/runner/.local/share/safe/client
   #   steps:
   #     - uses: actions/checkout@v4
 
@@ -1212,6 +1214,20 @@ jobs:
   #           echo "SAFE_PEERS has been set to $SAFE_PEERS"
   #         fi
 
+  # - name: Sleep 15s
+  #   shell: bash
+  #   run: sleep 15
+
+  # - name: Check faucet has been funded
+  #   shell: bash
+  #   run: |
+  #     cash_note_count=$(ls -l /home/runner/.local/share/safe/test_faucet/wallet/cash_notes/ | wc -l)
+  #     echo $cash_note_count
+  #     if [ "$cash_note_count" -eq 0 ]; then
+  #       echo "Error: Expected at least 1 cash note, but found $cash_note_count"
+  #       exit 1
+  #     fi
+
   # - name: Create and fund a wallet to pay for files storage
   #   run: |
   #     ./target/release/safe --log-output-dest=data-dir wallet create --no-password
@@ -1251,8 +1267,7 @@ jobs:
   #       echo "Got too many payment files leftover: $payment_files"
   #       exit 1
   #     fi
-  #   env:
-  #     CLIENT_DATA_PATH: /home/runner/.local/share/safe/client
+
   #   timeout-minutes: 10
 
   #     - name: Wait for certain period
@@ -1265,28 +1280,26 @@ jobs:
   #         SN_LOG: "all"
   #       timeout-minutes: 10
 
-  #     - name: Ensure no leftover cash_notes and payment files
-  #       run: |
-  #         expected_cash_notes_files="1"
-  #         expected_payment_files="0"
-  #         pwd
-  #         ls $CLIENT_DATA_PATH/ -l
-  #         ls $CLIENT_DATA_PATH/wallet -l
-  #         ls $CLIENT_DATA_PATH/wallet/cash_notes -l
-  #         cash_note_files=$(find $CLIENT_DATA_PATH/wallet/cash_notes -type f | wc -l)
-  #         if (( $(echo "$cash_note_files > $expected_cash_notes_files" | bc -l) )); then
-  #           echo "Got too many cash_note files leftover: $cash_note_files when we expected $expected_cash_notes_files"
-  #           exit 1
-  #         fi
-  #         ls $CLIENT_DATA_PATH/wallet/payments -l
-  #         payment_files=$(find $CLIENT_DATA_PATH/wallet/payments -type f | wc -l)
-  #         if (( $(echo "$payment_files > $expected_payment_files" | bc -l) )); then
-  #           echo "Got too many payment files leftover: $payment_files"
-  #           exit 1
-  #         fi
-  #       env:
-  #         CLIENT_DATA_PATH: /home/runner/.local/share/safe/client
-  #       timeout-minutes: 10
+  # - name: Ensure no leftover cash_notes and payment files
+  #   run: |
+  #     expected_cash_notes_files="1"
+  #     expected_payment_files="0"
+  #     pwd
+  #     ls $CLIENT_DATA_PATH/ -l
+  #     ls $CLIENT_DATA_PATH/wallet -l
+  #     ls $CLIENT_DATA_PATH/wallet/cash_notes -l
+  #     cash_note_files=$(find $CLIENT_DATA_PATH/wallet/cash_notes -type f | wc -l)
+  #     if (( $(echo "$cash_note_files > $expected_cash_notes_files" | bc -l) )); then
+  #       echo "Got too many cash_note files leftover: $cash_note_files when we expected $expected_cash_notes_files"
+  #       exit 1
+  #     fi
+  #     ls $CLIENT_DATA_PATH/wallet/payments -l
+  #     payment_files=$(find $CLIENT_DATA_PATH/wallet/payments -type f | wc -l)
+  #     if (( $(echo "$payment_files > $expected_payment_files" | bc -l) )); then
+  #       echo "Got too many payment files leftover: $payment_files"
+  #       exit 1
+  #     fi
+  #   timeout-minutes: 10
 
   #     - name: Wait for certain period
   #       run: sleep 300
@@ -1309,7 +1322,6 @@ jobs:
   #   env:
   #     SN_LOG: "all"
   #     SAFE_DATA_PATH: /home/runner/.local/share/safe
-  #     CLIENT_DATA_PATH: /home/runner/.local/share/safe/client
   #   timeout-minutes: 25
 
   #     - name: Use second client to upload third file
@@ -1318,29 +1330,27 @@ jobs:
   #         SN_LOG: "all"
   #       timeout-minutes: 10
 
-  #     - name: Ensure no leftover cash_notes and payment files
-  #       run: |
-  #         expected_cash_notes_files="1"
-  #         expected_payment_files="0"
-  #         pwd
-  #         ls $CLIENT_DATA_PATH/ -l
-  #         ls $CLIENT_DATA_PATH/wallet -l
-  #         ls $CLIENT_DATA_PATH/wallet/cash_notes -l
-  #         cash_note_files=$(ls $CLIENT_DATA_PATH/wallet/cash_notes | wc -l)
-  #         echo "Find $cash_note_files cash_note files"
-  #         if [ $expected_cash_notes_files -lt $cash_note_files ]; then
-  #           echo "Got too many cash_note files leftover: $cash_note_files"
-  #           exit 1
-  #         fi
-  #         ls $CLIENT_DATA_PATH/wallet/payments -l
-  #         payment_files=$(ls $CLIENT_DATA_PATH/wallet/payments | wc -l)
-  #         if [ $expected_payment_files -lt $payment_files ]; then
-  #           echo "Got too many payment files leftover: $payment_files"
-  #           exit 1
-  #         fi
-  #       env:
-  #         CLIENT_DATA_PATH: /home/runner/.local/share/safe/client
-  #       timeout-minutes: 10
+  # - name: Ensure no leftover cash_notes and payment files
+  #   run: |
+  #     expected_cash_notes_files="1"
+  #     expected_payment_files="0"
+  #     pwd
+  #     ls $CLIENT_DATA_PATH/ -l
+  #     ls $CLIENT_DATA_PATH/wallet -l
+  #     ls $CLIENT_DATA_PATH/wallet/cash_notes -l
+  #     cash_note_files=$(ls $CLIENT_DATA_PATH/wallet/cash_notes | wc -l)
+  #     echo "Find $cash_note_files cash_note files"
+  #     if [ $expected_cash_notes_files -lt $cash_note_files ]; then
+  #       echo "Got too many cash_note files leftover: $cash_note_files"
+  #       exit 1
+  #     fi
+  #     ls $CLIENT_DATA_PATH/wallet/payments -l
+  #     payment_files=$(ls $CLIENT_DATA_PATH/wallet/payments | wc -l)
+  #     if [ $expected_payment_files -lt $payment_files ]; then
+  #       echo "Got too many payment files leftover: $payment_files"
+  #       exit 1
+  #     fi
+  #   timeout-minutes: 10
 
   #     - name: Stop the local network and upload logs
   #       if: always()
