fix(CI): remove strict check
There is node churning during the memcheck and location verification
tests, which does havea chance of failed fetch alarm against dead node.
Hence move the check only to be undertaken withn the large file test,
which all nodes are persistant.

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -902,16 +902,6 @@ jobs:
           node_count=$(ls "${{ matrix.node_data_path }}" | wc -l)
           echo "Node dir count is $node_count"
 
-      - name: check there is no failed replication fetch
-        if: matrix.os != 'windows-latest' # causes error
-        shell: bash
-        run: |
-          if grep -r "failed to fetch" "${{ matrix.node_data_path }}"
-          then
-            echo "We find failed replication fetch"
-            exit 1
-          fi
-
       # Only error out after uploading the logs
       - name: Don't log raw data
         if: matrix.os != 'windows-latest' # causes error
@@ -1029,6 +1019,18 @@ jobs:
           log_file_prefix: safe_test_logs_large_file_upload
           build: true
 
+      - name: check there is no failed replication fetch
+        shell: bash
+        run: |
+          if grep -r "failed to fetch" $NODE_DATA_PATH
+          then
+            echo "We find failed replication fetch"
+            exit 1
+          fi
+        env:
+          NODE_DATA_PATH: /home/runner/.local/share/safe/node
+        timeout-minutes: 1
+
       - name: Check the home dir leftover space
         run: |
           df
@@ -1043,7 +1045,7 @@ jobs:
           ls $CLIENT_DATA_PATH/logs -l
         env:
           CLIENT_DATA_PATH: /home/runner/.local/share/safe/client
-        timeout-minutes: 10
+        timeout-minutes: 1
 
   replication_bench_with_heavy_upload:
     if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
