chore(ci): install ripgrep and move rg step after log fetch

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -360,15 +360,6 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
 
-      # - name: Download the Deployment Inventory
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: wan_testnet_deployment_inventory
-      #     path: /home/runner/wan_testnet_deployment_inventory.json
-
-      # - name: Set the SN_INVENTORY variable
-      #   run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
-
       - name: Check env variables
         shell: bash
         run: |
@@ -479,6 +470,9 @@ jobs:
       - name: Install Rust
         uses: dtolnay/rust-toolchain@stable
 
+      - name: install ripgrep
+        run: sudo apt-get -y install ripgrep
+
       - uses: Swatinem/rust-cache@v2
         continue-on-error: true
 
@@ -508,15 +502,6 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
 
-      # - name: Download the Deployment Inventory
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: wan_testnet_deployment_inventory
-      #     path: /home/runner/wan_testnet_deployment_inventory.json
-
-      # - name: Set the SN_INVENTORY variable
-      #   run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
-
       - name: Check env variables
         shell: bash
         run: |
@@ -534,48 +519,6 @@ jobs:
           TEST_CHURN_CYCLES: 2
           SN_LOG: "all"
         timeout-minutes: 90
-      
-      - name: Verify restart of nodes using rg
-        shell: bash
-        timeout-minutes: 1
-        # get the counts, then the specific line, and then the digit count only
-        # then check we have an expected level of restarts
-        # TODO: make this use an env var, or relate to testnet size
-        run : |
-          restart_count=$(rg "Node is restarting in" "${{ matrix.wan_logs_path }}" -c --stats | \
-            rg "(\d+) matches" | rg "\d+" -o)
-          echo "Restart $restart_count nodes"
-          peer_removed=$(rg "PeerRemovedFromRoutingTable" "${{ matrix.wan_logs_path }}" -c --stats | \
-            rg "(\d+) matches" | rg "\d+" -o)
-          echo "PeerRemovedFromRoutingTable $peer_removed times"
-          if [ $peer_removed -lt $restart_count ]; then
-            echo "PeerRemovedFromRoutingTable times of: $peer_removed is less than the restart count of: $restart_count"
-            exit 1
-          fi
-          node_count=$(find "${{ matrix.wan_logs_path }}" -type d | awk -F/ 'NF==6' | grep -E "/12D3KooW" | wc -l)
-          echo "Node dir count is $node_count"
-        # TODO: reenable this once the testnet dir creation is tidied up to avoid a large count here
-
-        # if [ $restart_count -lt $node_count ]; then
-        #   echo "Restart count of: $restart_count is less than the node count of: $node_count"
-        #   exit 1
-        # fi
-
-      - name: Verify data replication using rg
-        shell: bash
-        timeout-minutes: 1
-        # get the counts, then the specific line, and then the digit count only
-        # then check we have an expected level of replication
-        # TODO: make this use an env var, or relate to testnet size
-        run : |
-          fetching_attempt_count=$(rg "FetchingKeysForReplication" "${{ matrix.node_data_path }}" -c --stats | \
-            rg "(\d+) matches" | rg "\d+" -o)
-          echo "Carried out $fetching_attempt_count fetching attempts"
-          node_count=$(find "${{ matrix.wan_logs_path }}" -type d | awk -F/ 'NF==6' | grep -E "/12D3KooW" | wc -l)
-          if [ $fetching_attempt_count -lt $node_count ]; then
-            echo "Replication fetching attempts of: $fetching_attempt_count is less than the node count of: $node_count"
-            exit 1
-          fi
 
       - name: Fetch network logs
         if: always()
@@ -629,13 +572,47 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
       
-      # - name: post notification to slack on failure
-      #   if: ${{ failure() }}
-      #   uses: bryannice/gitactions-slack-notification@2.0.0
-      #   env:
-      #     SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_GH_ACTIONS_WEBHOOK_URL }}
-      #     SLACK_MESSAGE: "Please check the logs for the run at ${{ env.WORKFLOW_URL }}/${{ github.run_id }}"
-      #     SLACK_TITLE: "Nightly Churn Test Run Failed"
+      - name: Verify restart of nodes using rg
+        shell: bash
+        timeout-minutes: 1
+        # get the counts, then the specific line, and then the digit count only
+        # then check we have an expected level of restarts
+        # TODO: make this use an env var, or relate to testnet size
+        run : |
+          restart_count=$(rg "Node is restarting in" "${{ matrix.wan_logs_path }}" -c --stats | \
+            rg "(\d+) matches" | rg "\d+" -o)
+          echo "Restart $restart_count nodes"
+          peer_removed=$(rg "PeerRemovedFromRoutingTable" "${{ matrix.wan_logs_path }}" -c --stats | \
+            rg "(\d+) matches" | rg "\d+" -o)
+          echo "PeerRemovedFromRoutingTable $peer_removed times"
+          if [ $peer_removed -lt $restart_count ]; then
+            echo "PeerRemovedFromRoutingTable times of: $peer_removed is less than the restart count of: $restart_count"
+            exit 1
+          fi
+          node_count=$(find "${{ matrix.wan_logs_path }}" -type d | awk -F/ 'NF==6' | grep -E "/12D3KooW" | wc -l)
+          echo "Node dir count is $node_count"
+        # TODO: reenable this once the testnet dir creation is tidied up to avoid a large count here
+
+        # if [ $restart_count -lt $node_count ]; then
+        #   echo "Restart count of: $restart_count is less than the node count of: $node_count"
+        #   exit 1
+        # fi
+
+      - name: Verify data replication using rg
+        shell: bash
+        timeout-minutes: 1
+        # get the counts, then the specific line, and then the digit count only
+        # then check we have an expected level of replication
+        # TODO: make this use an env var, or relate to testnet size
+        run : |
+          fetching_attempt_count=$(rg "FetchingKeysForReplication" "${{ matrix.node_data_path }}" -c --stats | \
+            rg "(\d+) matches" | rg "\d+" -o)
+          echo "Carried out $fetching_attempt_count fetching attempts"
+          node_count=$(find "${{ matrix.wan_logs_path }}" -type d | awk -F/ 'NF==6' | grep -E "/12D3KooW" | wc -l)
+          if [ $fetching_attempt_count -lt $node_count ]; then
+            echo "Replication fetching attempts of: $fetching_attempt_count is less than the node count of: $node_count"
+            exit 1
+          fi
 
       # Only error out after uploading the logs
       - name: Don't log raw data
@@ -654,6 +631,15 @@ jobs:
             echo "We are logging an extremely large data"
             exit 1
           fi
+
+      # - name: post notification to slack on failure
+      #   if: ${{ failure() }}
+      #   uses: bryannice/gitactions-slack-notification@2.0.0
+      #   env:
+      #     SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_GH_ACTIONS_WEBHOOK_URL }}
+      #     SLACK_MESSAGE: "Please check the logs for the run at ${{ env.WORKFLOW_URL }}/${{ github.run_id }}"
+      #     SLACK_TITLE: "Nightly Churn Test Run Failed"
+
 
   verify_data_location_routing_table:
     name: Verify data location and Routing Table
@@ -675,6 +661,9 @@ jobs:
 
       - name: Install Rust
         uses: dtolnay/rust-toolchain@stable
+
+      - name: install ripgrep
+        run: sudo apt-get -y install ripgrep
 
       - uses: Swatinem/rust-cache@v2
         continue-on-error: true
@@ -705,15 +694,6 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
 
-      # - name: Download the Deployment Inventory
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: wan_testnet_deployment_inventory_NightlyDataLocationTest
-      #     path: /home/runner/wan_testnet_deployment_inventory.json
-
-      # - name: Set the SN_INVENTORY variable
-      #   run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
-
       - name: Check env variables
         shell: bash
         run: |
@@ -733,32 +713,6 @@ jobs:
       - name: Verify the routing tables of the nodes
         run: cargo test --release -p sn_node --test verify_routing_table -- --nocapture 
         timeout-minutes: 5
-      
-      - name: Verify restart of nodes using rg
-        shell: bash
-        timeout-minutes: 1
-        # get the counts, then the specific line, and then the digit count only
-        # then check we have an expected level of restarts
-        # TODO: make this use an env var, or relate to testnet size
-        run : |
-          restart_count=$(rg "Node is restarting in" "${{ matrix.wan_logs_path }}" -c --stats | \
-            rg "(\d+) matches" | rg "\d+" -o)
-          echo "Restart $restart_count nodes"
-          peer_removed=$(rg "PeerRemovedFromRoutingTable" "${{ matrix.wan_logs_path }}" -c --stats | \
-            rg "(\d+) matches" | rg "\d+" -o)
-          echo "PeerRemovedFromRoutingTable $peer_removed times"
-          if [ $peer_removed -lt $restart_count ]; then
-            echo "PeerRemovedFromRoutingTable times of: $peer_removed is less than the restart count of: $restart_count"
-            exit 1
-          fi
-          node_count=$(find "${{ matrix.wan_logs_path }}" -type d | awk -F/ 'NF==6' | grep -E "/12D3KooW" | wc -l)
-          echo "Node dir count is $node_count"
-        # TODO: reenable this once the testnet dir creation is tidied up to avoid a large count here
-
-        # if [ $restart_count -lt $node_count ]; then
-        #   echo "Restart count of: $restart_count is less than the node count of: $node_count"
-        #   exit 1
-        # fi
 
       - name: Fetch network logs
         if: always()
@@ -811,14 +765,32 @@ jobs:
           custom-node-bin-branch-name: wan_nightly
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
-      
-      # - name: post notification to slack on failure
-      #   if: ${{ failure() }}
-      #   uses: bryannice/gitactions-slack-notification@2.0.0
-      #   env:
-      #     SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_GH_ACTIONS_WEBHOOK_URL }}
-      #     SLACK_MESSAGE: "Please check the logs for the run at ${{ env.WORKFLOW_URL }}/${{ github.run_id }}"
-      #     SLACK_TITLE: "Nightly Data Location Test Run Failed"
+
+      - name: Verify restart of nodes using rg
+        shell: bash
+        timeout-minutes: 1
+        # get the counts, then the specific line, and then the digit count only
+        # then check we have an expected level of restarts
+        # TODO: make this use an env var, or relate to testnet size
+        run : |
+          restart_count=$(rg "Node is restarting in" "${{ matrix.wan_logs_path }}" -c --stats | \
+            rg "(\d+) matches" | rg "\d+" -o)
+          echo "Restart $restart_count nodes"
+          peer_removed=$(rg "PeerRemovedFromRoutingTable" "${{ matrix.wan_logs_path }}" -c --stats | \
+            rg "(\d+) matches" | rg "\d+" -o)
+          echo "PeerRemovedFromRoutingTable $peer_removed times"
+          if [ $peer_removed -lt $restart_count ]; then
+            echo "PeerRemovedFromRoutingTable times of: $peer_removed is less than the restart count of: $restart_count"
+            exit 1
+          fi
+          node_count=$(find "${{ matrix.wan_logs_path }}" -type d | awk -F/ 'NF==6' | grep -E "/12D3KooW" | wc -l)
+          echo "Node dir count is $node_count"
+        # TODO: reenable this once the testnet dir creation is tidied up to avoid a large count here
+
+        # if [ $restart_count -lt $node_count ]; then
+        #   echo "Restart count of: $restart_count is less than the node count of: $node_count"
+        #   exit 1
+        # fi
 
       # Only error out after uploading the logs
       - name: Don't log raw data
@@ -837,3 +809,11 @@ jobs:
             echo "We are logging an extremely large data"
             exit 1
           fi
+
+      # - name: post notification to slack on failure
+      #   if: ${{ failure() }}
+      #   uses: bryannice/gitactions-slack-notification@2.0.0
+      #   env:
+      #     SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_GH_ACTIONS_WEBHOOK_URL }}
+      #     SLACK_MESSAGE: "Please check the logs for the run at ${{ env.WORKFLOW_URL }}/${{ github.run_id }}"
+      #     SLACK_TITLE: "Nightly Data Location Test Run Failed"
