chore(ci): set SN_INVENTORY using the testnet action

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -65,9 +65,11 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
 
-      - name: Check contact peer
+      - name: Check env variables
         shell: bash
-        run: echo "Peer is $SAFE_PEERS"
+        run: |
+          echo "Peer is $SAFE_PEERS"
+          echo "Deployment inventory is $SN_INVENTORY"
 
       - name: Create and fund a wallet to pay for files storage
         run: |
@@ -246,9 +248,11 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
 
-      - name: Check contact peer
+      - name: Check env variables
         shell: bash
-        run: echo "Peer is $SAFE_PEERS"
+        run: |
+          echo "Peer is $SAFE_PEERS"
+          echo "Deployment inventory is $SN_INVENTORY"
 
       - name: Gossipsub - nodes to subscribe to topics, and publish messages 
         run: cargo test --release -p sn_node --test msgs_over_gossipsub -- --nocapture
@@ -337,14 +341,20 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
 
-      - name: Download the Deployment Inventory
-        uses: actions/download-artifact@v3
-        with:
-          name: wan_testnet_deployment_inventory
-          path: /home/runner/wan_testnet_deployment_inventory.json
+      # - name: Download the Deployment Inventory
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: wan_testnet_deployment_inventory
+      #     path: /home/runner/wan_testnet_deployment_inventory.json
 
-      - name: Set the SN_INVENTORY variable
-        run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
+      # - name: Set the SN_INVENTORY variable
+      #   run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
+
+      - name: Check env variables
+        shell: bash
+        run: |
+          echo "Peer is $SAFE_PEERS"
+          echo "Deployment inventory is $SN_INVENTORY"
 
       # This should be first to avoid slow reward acceptance etc
       - name: execute the nodes rewards tests
@@ -469,20 +479,30 @@ jobs:
           testnet-tool-repo-user: RolandSherwin
           testnet-tool-repo-branch: wan_nightly
 
-      - name: Download the Deployment Inventory
-        uses: actions/download-artifact@v3
-        with:
-          name: wan_testnet_deployment_inventory
-          path: /home/runner/wan_testnet_deployment_inventory.json
+      # - name: Download the Deployment Inventory
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: wan_testnet_deployment_inventory
+      #     path: /home/runner/wan_testnet_deployment_inventory.json
 
-      - name: Set the SN_INVENTORY variable
-        run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
+      # - name: Set the SN_INVENTORY variable
+      #   run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
 
-      - name: Chunks data integrity during nodes churn (during 10min) (in theory)
+      - name: Check env variables
+        shell: bash
+        run: |
+          echo "Peer is $SAFE_PEERS"
+          echo "Deployment inventory is $SN_INVENTORY"
+
+      - name: Chunks data integrity during nodes churn
         run: cargo test --release -p sn_node --test data_with_churn -- --nocapture
         env:
-          TEST_DURATION_MINS: 60
-          TEST_CHURN_CYCLES: 6
+          # TEST_DURATION_MINS: 60
+          # TEST_CHURN_CYCLES: 6
+          # SN_LOG: "all"
+          # todo: lower time for testing
+          TEST_DURATION_MINS: 10
+          TEST_CHURN_CYCLES: 2
           SN_LOG: "all"
         timeout-minutes: 90
       
@@ -591,156 +611,162 @@ jobs:
       #     fi
 
   verify_data_location_routing_table:
-      name: Verify data location and Routing Table
-      runs-on: ${{ matrix.os }}
-      strategy:
-        matrix:
-          include:
-            - os: ubuntu-latest
-              node_data_path: /home/runner/.local/share/safe/node
-              safe_path: /home/runner/.local/share/safe
-            # - os: windows-latest
-            #   node_data_path: C:\\Users\\runneradmin\\AppData\\Roaming\\safe\\node
-            #   safe_path: C:\\Users\\runneradmin\\AppData\\Roaming\\safe
-            # - os: macos-latest
-            #   node_data_path: /Users/runner/Library/Application Support/safe/node
-            #   safe_path: /Users/runner/Library/Application Support/safe
-      steps:
-        - uses: actions/checkout@v4
+    name: Verify data location and Routing Table
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        include:
+          - os: ubuntu-latest
+            node_data_path: /home/runner/.local/share/safe/node
+            safe_path: /home/runner/.local/share/safe
+          # - os: windows-latest
+          #   node_data_path: C:\\Users\\runneradmin\\AppData\\Roaming\\safe\\node
+          #   safe_path: C:\\Users\\runneradmin\\AppData\\Roaming\\safe
+          # - os: macos-latest
+          #   node_data_path: /Users/runner/Library/Application Support/safe/node
+          #   safe_path: /Users/runner/Library/Application Support/safe
+    steps:
+      - uses: actions/checkout@v4
 
-        - name: Install Rust
-          uses: dtolnay/rust-toolchain@stable
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@stable
 
-        - uses: Swatinem/rust-cache@v2
-          continue-on-error: true
+      - uses: Swatinem/rust-cache@v2
+        continue-on-error: true
 
-        - name: Build data location and routing table tests
-          run: cargo test --release -p sn_node --test verify_data_location --test verify_routing_table --no-run
-          timeout-minutes: 30
+      - name: Build data location and routing table tests
+        run: cargo test --release -p sn_node --test verify_data_location --test verify_routing_table --no-run
+        timeout-minutes: 30
 
-        - name: Start a WAN network
-          uses: RolandSherwin/sn-testnet-action@wan_nightly
-          with:
-            action: create
-            rust-log: debug
-            ansible-vault-password: ${{ secrets.SN_TESTNET_ANSIBLE_VAULT_PASSWORD }}
-            aws-access-key-id: ${{ secrets.SN_TESTNET_AWS_ACCESS_KEY_ID }}
-            aws-access-key-secret: ${{ secrets.SN_TESTNET_AWS_SECRET_ACCESS_KEY }}
-            aws-region: eu-west-2
-            do-token: ${{ secrets.SN_TESTNET_DO_PAT }}
-            ssh-secret-key: ${{ secrets.SN_TESTNET_SSH_KEY }}
-            security-group-id: sg-0d47df5b3f0d01e2a
-            subnet-id: subnet-018f2ab26755df7f9
-            node-count: 20
-            vm-count: 1
-            provider: digital-ocean
-            testnet-name: NightlyDataLocationTest
-            custom-node-bin-org-name: maidsafe
-            custom-node-bin-branch-name: main
-            testnet-tool-repo-user: RolandSherwin
-            testnet-tool-repo-branch: wan_nightly
+      - name: Start a WAN network
+        uses: RolandSherwin/sn-testnet-action@wan_nightly
+        with:
+          action: create
+          rust-log: debug
+          ansible-vault-password: ${{ secrets.SN_TESTNET_ANSIBLE_VAULT_PASSWORD }}
+          aws-access-key-id: ${{ secrets.SN_TESTNET_AWS_ACCESS_KEY_ID }}
+          aws-access-key-secret: ${{ secrets.SN_TESTNET_AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-2
+          do-token: ${{ secrets.SN_TESTNET_DO_PAT }}
+          ssh-secret-key: ${{ secrets.SN_TESTNET_SSH_KEY }}
+          security-group-id: sg-0d47df5b3f0d01e2a
+          subnet-id: subnet-018f2ab26755df7f9
+          node-count: 20
+          vm-count: 1
+          provider: digital-ocean
+          testnet-name: NightlyDataLocationTest
+          custom-node-bin-org-name: maidsafe
+          custom-node-bin-branch-name: main
+          testnet-tool-repo-user: RolandSherwin
+          testnet-tool-repo-branch: wan_nightly
 
-        - name: Download the Deployment Inventory
-          uses: actions/download-artifact@v3
-          with:
-            name: wan_testnet_deployment_inventory
-            path: /home/runner/wan_testnet_deployment_inventory.json
+      # - name: Download the Deployment Inventory
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: wan_testnet_deployment_inventory_NightlyDataLocationTest
+      #     path: /home/runner/wan_testnet_deployment_inventory.json
 
-        - name: Set the SN_INVENTORY variable
-          run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
+      # - name: Set the SN_INVENTORY variable
+      #   run: echo "SN_INVENTORY=/home/runner/wan_testnet_deployment_inventory.json" >> $GITHUB_ENV
 
-        - name: Verify the Routing table of the nodes
-          run: cargo test --release -p sn_node --test verify_routing_table -- --nocapture
-          timeout-minutes: 5
+      - name: Check env variables
+        shell: bash
+        run: |
+          echo "Peer is $SAFE_PEERS"
+          echo "Deployment inventory is $SN_INVENTORY"
 
-        - name: Verify the location of the data on the network
-          run: cargo test --release -p sn_node --test verify_data_location -- --nocapture
-          env:
-            SN_LOG: "all"
-          timeout-minutes: 90
+      - name: Verify the Routing table of the nodes
+        run: cargo test --release -p sn_node --test verify_routing_table -- --nocapture
+        timeout-minutes: 5
 
-        - name: Verify the routing tables of the nodes
-          run: cargo test --release -p sn_node --test verify_routing_table -- --nocapture 
-          timeout-minutes: 5
-        
-        # - name: Verify restart of nodes using rg
-        #   shell: bash
-        #   timeout-minutes: 1
-        #   # get the counts, then the specific line, and then the digit count only
-        #   # then check we have an expected level of restarts
-        #   # TODO: make this use an env var, or relate to testnet size
-        #   run : |
-        #     restart_count=$(rg "Node is restarting in" "${{ matrix.node_data_path }}" -c --stats | \
-        #       rg "(\d+) matches" | rg "\d+" -o)
-        #     echo "Restart $restart_count nodes"
-        #     peer_removed=$(rg "PeerRemovedFromRoutingTable" "${{ matrix.node_data_path }}" -c --stats | \
-        #       rg "(\d+) matches" | rg "\d+" -o)
-        #     echo "PeerRemovedFromRoutingTable $peer_removed times"
-        #     if [ $peer_removed -lt $restart_count ]; then
-        #       echo "PeerRemovedFromRoutingTable times of: $peer_removed is less than the restart count of: $restart_count"
-        #       exit 1
-        #     fi
-        #     node_count=$(ls "${{ matrix.node_data_path }}" | wc -l)
-        #     echo "Node dir count is $node_count"
+      - name: Verify the location of the data on the network
+        run: cargo test --release -p sn_node --test verify_data_location -- --nocapture
+        env:
+          SN_LOG: "all"
+        timeout-minutes: 90
 
-        - name: Fetch network logs
-          if: always()
-          uses: RolandSherwin/sn-testnet-action@wan_nightly
-          with:
-            action: logs
-            rust-log: debug
-            ansible-vault-password: ${{ secrets.SN_TESTNET_ANSIBLE_VAULT_PASSWORD }}
-            aws-access-key-id: ${{ secrets.SN_TESTNET_AWS_ACCESS_KEY_ID }}
-            aws-access-key-secret: ${{ secrets.SN_TESTNET_AWS_SECRET_ACCESS_KEY }}
-            aws-region: eu-west-2
-            do-token: ${{ secrets.SN_TESTNET_DO_PAT }}
-            ssh-secret-key: ${{ secrets.SN_TESTNET_SSH_KEY }}
-            node-count: 20
-            vm-count: 1
-            provider: digital-ocean
-            testnet-name: NightlyDataLocationTest
-            custom-node-bin-org-name: maidsafe
-            custom-node-bin-branch-name: main
-            testnet-tool-repo-user: RolandSherwin
-            testnet-tool-repo-branch: wan_nightly
+      - name: Verify the routing tables of the nodes
+        run: cargo test --release -p sn_node --test verify_routing_table -- --nocapture 
+        timeout-minutes: 5
+      
+      # - name: Verify restart of nodes using rg
+      #   shell: bash
+      #   timeout-minutes: 1
+      #   # get the counts, then the specific line, and then the digit count only
+      #   # then check we have an expected level of restarts
+      #   # TODO: make this use an env var, or relate to testnet size
+      #   run : |
+      #     restart_count=$(rg "Node is restarting in" "${{ matrix.node_data_path }}" -c --stats | \
+      #       rg "(\d+) matches" | rg "\d+" -o)
+      #     echo "Restart $restart_count nodes"
+      #     peer_removed=$(rg "PeerRemovedFromRoutingTable" "${{ matrix.node_data_path }}" -c --stats | \
+      #       rg "(\d+) matches" | rg "\d+" -o)
+      #     echo "PeerRemovedFromRoutingTable $peer_removed times"
+      #     if [ $peer_removed -lt $restart_count ]; then
+      #       echo "PeerRemovedFromRoutingTable times of: $peer_removed is less than the restart count of: $restart_count"
+      #       exit 1
+      #     fi
+      #     node_count=$(ls "${{ matrix.node_data_path }}" | wc -l)
+      #     echo "Node dir count is $node_count"
 
-        - name: Stop the WAN network
-          if: always()
-          uses: RolandSherwin/sn-testnet-action@wan_nightly
-          with:
-            action: destroy
-            rust-log: debug
-            ansible-vault-password: ${{ secrets.SN_TESTNET_ANSIBLE_VAULT_PASSWORD }}
-            aws-access-key-id: ${{ secrets.SN_TESTNET_AWS_ACCESS_KEY_ID }}
-            aws-access-key-secret: ${{ secrets.SN_TESTNET_AWS_SECRET_ACCESS_KEY }}
-            aws-region: eu-west-2
-            do-token: ${{ secrets.SN_TESTNET_DO_PAT }}
-            ssh-secret-key: ${{ secrets.SN_TESTNET_SSH_KEY }}
-            node-count: 20
-            vm-count: 1
-            provider: digital-ocean
-            testnet-name: NightlyDataLocationTest
-            custom-node-bin-org-name: maidsafe
-            custom-node-bin-branch-name: main
-            testnet-tool-repo-user: RolandSherwin
-            testnet-tool-repo-branch: wan_nightly
-        
-        # - name: post notification to slack on failure
-        #   if: ${{ failure() }}
-        #   uses: bryannice/gitactions-slack-notification@2.0.0
-        #   env:
-        #     SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_GH_ACTIONS_WEBHOOK_URL }}
-        #     SLACK_MESSAGE: "Please check the logs for the run at ${{ env.WORKFLOW_URL }}/${{ github.run_id }}"
-        #     SLACK_TITLE: "Nightly Data Location Test Run Failed"
+      - name: Fetch network logs
+        if: always()
+        uses: RolandSherwin/sn-testnet-action@wan_nightly
+        with:
+          action: logs
+          rust-log: debug
+          ansible-vault-password: ${{ secrets.SN_TESTNET_ANSIBLE_VAULT_PASSWORD }}
+          aws-access-key-id: ${{ secrets.SN_TESTNET_AWS_ACCESS_KEY_ID }}
+          aws-access-key-secret: ${{ secrets.SN_TESTNET_AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-2
+          do-token: ${{ secrets.SN_TESTNET_DO_PAT }}
+          ssh-secret-key: ${{ secrets.SN_TESTNET_SSH_KEY }}
+          node-count: 20
+          vm-count: 1
+          provider: digital-ocean
+          testnet-name: NightlyDataLocationTest
+          custom-node-bin-org-name: maidsafe
+          custom-node-bin-branch-name: main
+          testnet-tool-repo-user: RolandSherwin
+          testnet-tool-repo-branch: wan_nightly
 
-        # # Only error out after uploading the logs
-        # - name: Don't log raw data
-        #   if: matrix.os != 'windows-latest' # causes error
-        #   shell: bash
-        #   timeout-minutes: 10
-        #   run: |
-        #     if ! rg '^' "${{ matrix.safe_path }}"/*/*/logs | awk 'length($0) > 15000 { print; exit 1 }'
-        #     then
-        #       echo "We are logging an extremely large data"
-        #       exit 1
-        #     fi
+      - name: Stop the WAN network
+        if: always()
+        uses: RolandSherwin/sn-testnet-action@wan_nightly
+        with:
+          action: destroy
+          rust-log: debug
+          ansible-vault-password: ${{ secrets.SN_TESTNET_ANSIBLE_VAULT_PASSWORD }}
+          aws-access-key-id: ${{ secrets.SN_TESTNET_AWS_ACCESS_KEY_ID }}
+          aws-access-key-secret: ${{ secrets.SN_TESTNET_AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-2
+          do-token: ${{ secrets.SN_TESTNET_DO_PAT }}
+          ssh-secret-key: ${{ secrets.SN_TESTNET_SSH_KEY }}
+          node-count: 20
+          vm-count: 1
+          provider: digital-ocean
+          testnet-name: NightlyDataLocationTest
+          custom-node-bin-org-name: maidsafe
+          custom-node-bin-branch-name: main
+          testnet-tool-repo-user: RolandSherwin
+          testnet-tool-repo-branch: wan_nightly
+      
+      # - name: post notification to slack on failure
+      #   if: ${{ failure() }}
+      #   uses: bryannice/gitactions-slack-notification@2.0.0
+      #   env:
+      #     SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_GH_ACTIONS_WEBHOOK_URL }}
+      #     SLACK_MESSAGE: "Please check the logs for the run at ${{ env.WORKFLOW_URL }}/${{ github.run_id }}"
+      #     SLACK_TITLE: "Nightly Data Location Test Run Failed"
+
+      # # Only error out after uploading the logs
+      # - name: Don't log raw data
+      #   if: matrix.os != 'windows-latest' # causes error
+      #   shell: bash
+      #   timeout-minutes: 10
+      #   run: |
+      #     if ! rg '^' "${{ matrix.safe_path }}"/*/*/logs | awk 'length($0) > 15000 { print; exit 1 }'
+      #     then
+      #       echo "We are logging an extremely large data"
+      #       exit 1
+      #     fi
